### ISSUE TITLE
Mudar instrução de entrega no README.md

### ISSUE THREAD

**Issue by maufonseca** [btgpactualdigitaldev/mobile-challenge#37]
Não parece possível algum candidato fazer um clone e depois push para o repositório do **btgpactualdigitaldev**, como está na documentação do repositório. 

Portanto a documentação do README.md poderia especificar corretamente, no último parágrafo, um **fork** para a conta do candidato no github, ao invés de um **clone**.

**Comment by MaatheusGois** [comment]
@maufonseca muito obrigado por seu comentário, o ajuste foi realizado 👍🏻
